### ISSUE TITLE
Default created file fail to be imported in uncrastifyx

### ISSUE THREAD

**Issue by ivan-golub** [benoitsan/BBUncrustifyPlugin-Xcode#90] opened 2015-03-13 12:56 UTC
After clean installation on xcode 6.2, BBUncrustifyPlugin-Xcode from Alcatraz and latest version of UncrustifyX. It just fails to open config file.

**Comment by benoitsan** [comment] 2015-03-17 20:45
I could not reproduce the issue. I installed BBUncrustifyPlugin using Alcatraz. The plugin version is 2.0.6. I built UncrustifyX from the master branch.

**Comment by ivan-golub** [comment] 2015-03-18 11:48
I tried again, but it still happens and way of installation has no influence, I tried with Alcatraz, by downloading latest release and with building source code.
XCode 6.2. Install BBUncrustifyPlugin with any method -> go to preferences -> press Create config file (Uncrastify) -> Try to Edit Uncrastify configuration with UncrustifyX.
As a result - error with many problems of format read and missing options
![screen shot 2015-03-18 at 13 40 12](https://cloud.githubusercontent.com/assets/1858309/6708039/73dc06ee-cd75-11e4-918a-5a6c462ab446.png)

**Comment by benoitsan** [comment] 2015-04-25 11:45
Hi Ivan,

I could reproduce the issue.

The error "could not find option" means that the Uncrustify configuration parameter is not recognized by UncrustifyX. If you look at the source code of UncrustifyX, there a `definitions.plist` but it misses recent configuration parameters.

It's not a bug related to the plugin. I close the issue.

**Closed by benoitsan** 2015-04-25 11:45 UTC
